services:
  pgdatabase: 
    image: postgres:13
    environment:
      - POSTGRES_USER=yash
      - POSTGRES_PASSWORD=yash
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=shahy.data@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=yash
    ports:
      - 8080:80